consumer:
	javac ConnectionLessConsumer.java

producer:
	javac ConnectionLessProducer.java

all: consumer producer

testconsumer:
	java ConnectionLessConsumer

testproducer:
	java ConnectionLessProducer

clean:
	rm *.class
